version: "3.1"

services:
  redmine:
    build: 
      context: ./docker/redmine
    environment:
      REDMINE_DB_POSTGRES: postgres
      REDMINE_DB_PASSWORD: postgres
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.${APP_NAME}-redirectscheme.redirectscheme.scheme=https"
      - "traefik.http.middlewares.${APP_NAME}-redirectscheme.redirectscheme.permanent=true"
      - "traefik.http.routers.${APP_NAME}-redmine.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}-redmine.middlewares=${APP_NAME}-redirectscheme"
    restart: always

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - default
      - web
    ports: 
      - 127.0.0.1:5432:5432
    restart: always

networks:
  web:
    external: true
