version: "3.1"

services:
  redmine:
    image: redmine:4-alpine
    environment:
      REDMINE_DB_POSTGRES: postgres
      REDMINE_DB_PASSWORD: postgres
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}-redmine.rule=Host(`${APP_DOMAIN}`)"
    restart: always

  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - default
      - web
    restart: always

volumes:
  postgres_data: ~

networks:
  web:
    external: true
